/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jay2307 (https://sketchfab.com/jay2307)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/millenium-falcon-64a83c7671274870889d19e1ecfb8ea6
Title: Millenium Falcon
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThee} from '@react-three/fiber';
import milleniumScene from '../public/millenium_falcon.glb';
import { a } from '@react-spring/three'; //enable animations

export function Model(props) {
  const { nodes, materials } = useGLTF(milleniumScene)
  const milleniumRef = useRef()
  return (
    <a.group {...props} dispose={null}>
      <group scale={0.365}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['modelsmap_objectsshipsfalcon_landing_gear.grid']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['modelsmap_objectsshipsfalcon_shield_front.grid']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['modelsmap_objectsshipsfalcon_cockpit.grid']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials['modelsmap_objectsshipsfalcon_front_parts.grid']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials['modelsmap_objectsshipsfalcon_thrusters.grid']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials['modelsmap_objectsshipsfalcon_shield_rear.grid']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials['modelsmap_objectsshipsfalcon_thrusters.grid']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials['modelsmap_objectsshipsfalcon_landing_gear.grid']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials['modelsmap_objectsshipsfalcon_landing_gear.grid']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials['modelsmap_objectsshipsfalcon_landing_gear.grid']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials['modelsmap_objectsshipsfalcon_landing_gear.grid']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials['modelsmap_objectsshipsfalcon_landing_gear.grid']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials['modelsmap_objectsshipsfalcon_disk.grid']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials['modelsmap_objectsshipsfalcon_shield_front.grid']}
        />
      </group>
    </a.group>
  )
}

useGLTF.preload('/millenium_falcon.glb')
